name: Docs Release

on:
  push:
    branches: 
      - master
    paths:
      - 'docs/**'
  release:
    types: [published]

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade sphinx sphinx-rtd-theme myst-parser sphinx-autodoc-typehints sphinx-copybutton sphinx-design sphinxcontrib-mermaid
        pip install -e .
        pip install -e .[dev]

    - name: List installed packages
      run: pip list

    - name: Build documentation
      run: |
        cd docs
        python -m sphinx -b html . _build/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: ${{ github.event.release.tag_name }}
